baseURL = "https://sovereign-tech-directory.eu/"
title = "Sovereign Tech Directory"
languageCode = "en-GB"
defaultContentLanguage = "en"
contentDir = "content/en"

[params]
  description = "A curated directory for digital sovereignty in Europe"

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-heroicons"
